<a href="https://colab.research.google.com/github/SanjeevReddy61/temp/blob/main/DM_EXP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.random import randn
from numpy.random import seed
from scipy.stats import pearsonr
seed(1)
#increasing the standard deviation of 20 and adding the mean of 100
data1=20*randn(1000)+100
print(data1)
data2=data1+(10*randn(1000)+50)
corr,_=pearsonr(data1,data2)
print('Pearsons correlation: %.3f' % corr)

[132.48690727  87.76487173  89.43656495  78.54062756 117.30815259
  53.96922606 134.89623528  84.77586198 106.38078192  95.01259249
 129.24215874  58.79718581  93.55165592  92.31891291 122.67538885
  78.00217465  96.55143585  82.44283164 100.84427493 111.65630427
  77.98761646 122.8944742  118.03181441 110.04988678 118.01711899
  86.32544282  97.54219549  81.28461131  94.64223841 110.60710933
  86.16678497  92.06492946  86.256546    83.09588717  86.57507738
  99.74670802  77.65379303 104.68831396 133.19604354 114.84088321
  96.16328895  82.24742072  85.05683412 133.84909202 101.0161551
  87.26008707 103.81830969 142.00510273 102.40317905 112.34406219
 106.0034064   92.95500307  77.14963604  93.01314555  95.82211533
 111.73246382 116.77966828 118.62204163 105.71174651 117.70282329
  84.91204118 125.0573631  110.25859641  94.0381433  109.77036293
  98.48856574 122.63258775 130.39633633 143.71150813  72.07007329
  71.11772389  89.91068274 103.20074139 117.52337842 106.31269894
  59.555975

In [ ]:
data1

NameError: name 'data1' is not defined

In [ ]:
data1[:5]

array([132.48690727,  87.76487173,  89.43656495,  78.54062756,
       117.30815259])

In [ ]:
from numpy.random import randn
single_value = randn(3,5)
print(single_value)

[[-2.17212271  0.19038724 -1.40522754  0.36986047 -0.2617817 ]
 [-0.83271351 -1.55378261 -0.68284784  0.31062382 -0.12544719]
 [ 0.6662438  -0.78833027  1.60599352 -0.23795342 -0.84519543]]


In [ ]:
from math import *
def square_rooted(x):
  return round(sqrt(sum([a*a for a in x])),3)
def cosine_similarity(x,y):
  numerator=sum(a*b for a,b in zip(x,y))
  denominator=square_rooted(x)*square_rooted(y)
  return round(numerator/float(denominator),3)
print(cosine_similarity([3,45,7,2],[2,54,13,15]))


0.972


In [ ]:
from math import *
def jaccard_similarity(x,y):
  intersection_cardinality=len(set.intersection(*[set(x),set(y)]))
  union_cardinality=len(set.union(*[set(x),set(y)]))
  return intersection_cardinality/float(union_cardinality)
print(jaccard_similarity([0,1,2,5,6],[0,2,3,5,7,9]))

0.375


In [ ]:
from math import *
def euclidean_distance(x,y):
  return sqrt(sum(pow(a-b,2) for a,b in zip(x,y)))
print(euclidean_distance([0,3,4,5],[7,6,3,-1]))

9.746794344808963


In [ ]:
from math import *
def manhattan_distance(x,y):
  return sum(abs(a-b) for a,b in zip(x,y))
print(manhattan_distance([10,20,10],[10,20,20]))

10


In [ ]:
seed(2)
d1=10*randn(500)+50
d2=d1+(10*randn(500)+30)
corr,_=pearsonr(d1,d2)
print(round(corr,4))

0.7426


In [ ]:
from math import *
def squareroot(x):
  return round(sqrt(sum([a*a for a in x])),3)
def cosinee(x,y):
  nume=sum(a*b for a,b in zip(x,y))
  deno=(squareroot(x) * squareroot(y))
  return(round(nume/deno,3))
print(cosinee([2,3,6,8],[6,2,4,7]))


0.9


sumation(sqrt(sum((x-y)^2)))

In [ ]:
def euclidien(x,y):
  return sqrt(sum(pow(x-y,2) for x,y in zip(x,y)))
print(euclidien([54,12,54,65],[21,54,32,15]))

76.40026177965623
